### PR TITLE
#4: Actually delete key when calling erase()

### PR DESCRIPTION
**Pull request by spiffytech**
- [ ] @fresc81 
- [x] @justinmchase
- [ ] @mikeyoon

### CODE REVIEW

**Comment by justinmchase** [comment]
`/va` appears to be a valid argument to reg delete:
```
/va        delete all values under this key.
```

What were you trying to do that this was causing a problem?

**Comment by spiffytech** [comment]
`/va` deletes the contents of the key, but leaves the key itself in place. This does not match the stated behavior of `erase` in the README, which claims `erase` deletes a key.

Further, without this patch, it's not clear that winreg can delete a key at all (i.e., it's unclear if `remove` can substitute for the patched [stated] behavior of `erase`).

I'm trying to pass winreg a path and have that registry entry and all of its children nuked.

**Comment by justinmchase** [comment]
So without `/va` if a key has values the key and all of the values are deleted? Sounds :+1: to me then.

**Comment by fresc81** [comment]
I think /VA only deletes the values. Should we use an additional method to delete keys and just update the docs for erase? I don't want to break the behaviour of this method in case it leads to problems with existing programs that depend on that behaviour.

**Comment by fresc81** [comment]
It's also already implemented in the tests-docs branch.
https://github.com/fresc81/node-winreg/blob/tests-docs/lib/registry.js#L663

**Comment by feross** [comment]
Can this be merged? I need this behavior in my program.

You don't need to worry about breaking existing code. That's what semantic versioning is for. Release it as version 2.0.0.

**Comment by feross** [comment]
I just sent a fresh PR that merges cleanly to fix this. Just tested it and it works perfectly :dizzy:

**Pull request closed without merging**
