### PR TITLE
Actually delete key when calling erase()

### LINKED ISSUE #4: Registry.erase(cb) leaves behind the key (while deleting all the name/value pairs).
This is because you use the `/va` argument.

      /va        delete all values under this key.

`Erase` is a good name for this operation, so I'd suggest updating the docs that it doesn't actually delete the key, and make another function that deletes the key and all descendant keys.

Just leave out the `/va` argument for the Registry.delete() function. Eg: https://github.com/Zren/atom-windows-context-menu/blob/master/lib/registry.js#L506

### PR DESCRIPTION
**Pull request by feross**
Fixes #4. Supersedes #22 and merges cleanly.

### CODE REVIEW

**Comment by mikeyoon** [comment]
I think based on the conversation in the previous PR, I personally would prefer backporting the delete() function from the test-docs branch. @fresc81 Think there'd be any issue with backporting the function?

**Comment by feross** [comment]
I can't think of any issues that would arise from adding a new `delete()` function in addition to the existing `erase()`. Let's do it. Want a PR, or would you like to do it?

**Comment by mikeyoon** [comment]
If you don't mind doing the PR that would be great. I don't spend as much time on windows machines as I used to at the moment.

**Comment by fresc81** [comment]
Sorry for the late response. Actually it would collide with the semantics of the delete funtion. I would give a new delete function the favour over changing the existing erase function. But I can do that today.

**Comment by fresc81** [comment]
But good to see the CI working properly xD

**Comment by fresc81** [comment]
so my plans for today: rename erase to clear and mark erase as being depricated, implement delete with the semantics suggested by @feross. Thats imo a cleaner solution and we can keep winreg at version 1.x.

**Comment by feross** [comment]
Thanks for the excellent work!

**Comment by feross** [comment]
Noticed some mistakes in the `destroy()` function that cause an exception! PR to fix it sent here: https://github.com/fresc81/node-winreg/pull/35

**Pull request closed without merging**
