### PR TITLE
Add support for specifying 32 or 64 bit hive

### PR DESCRIPTION
**Pull request by RX14**
This commit succeeds #11, which seems to be stalled.

### CODE REVIEW

**Comment by RX14** [comment]
Ok, been playing with this for a while, I think i've got most of the bugs and silly mistakes ironed out.

**Comment by mikeyoon** [comment]
Thanks for picking this one up. Got busy and don't do as much windows work nowadays.

**Comment by RX14** [comment]
Updated. I could do more to clean up the code, but that would be outside the scope of this PR.

**Comment by fresc81** [comment]
Allright tested on Windows XP (32 Bit), 7 and 10 (64 Bit). Works great. Thumps up from me.

**Pull request merged**
